package libsql

// Code generated by http://github.com/gojuno/minimock (dev). DO NOT EDIT.

import (
	"context"
	"database/sql"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// QueryerMock implements Queryer
type QueryerMock struct {
	t minimock.Tester

	funcScan          func(ctx context.Context, scanner RowScanner, sql string, args ...interface{}) (err error)
	inspectFuncScan   func(ctx context.Context, scanner RowScanner, sql string, args ...interface{})
	afterScanCounter  uint64
	beforeScanCounter uint64
	ScanMock          mQueryerMockScan

	funcScanOne          func(ctx context.Context, scanner RowScanner, sql string, args ...interface{}) (err error)
	inspectFuncScanOne   func(ctx context.Context, scanner RowScanner, sql string, args ...interface{})
	afterScanOneCounter  uint64
	beforeScanOneCounter uint64
	ScanOneMock          mQueryerMockScanOne

	funcUpdate          func(ctx context.Context, sql string, args ...interface{}) (r1 sql.Result, err error)
	inspectFuncUpdate   func(ctx context.Context, sql string, args ...interface{})
	afterUpdateCounter  uint64
	beforeUpdateCounter uint64
	UpdateMock          mQueryerMockUpdate

	funcUpdateAndGetLastInsertID          func(ctx context.Context, sql string, args ...interface{}) (i1 int64, err error)
	inspectFuncUpdateAndGetLastInsertID   func(ctx context.Context, sql string, args ...interface{})
	afterUpdateAndGetLastInsertIDCounter  uint64
	beforeUpdateAndGetLastInsertIDCounter uint64
	UpdateAndGetLastInsertIDMock          mQueryerMockUpdateAndGetLastInsertID

	funcUpdateAndGetRowsAffected          func(ctx context.Context, sql string, args ...interface{}) (i1 int64, err error)
	inspectFuncUpdateAndGetRowsAffected   func(ctx context.Context, sql string, args ...interface{})
	afterUpdateAndGetRowsAffectedCounter  uint64
	beforeUpdateAndGetRowsAffectedCounter uint64
	UpdateAndGetRowsAffectedMock          mQueryerMockUpdateAndGetRowsAffected
}

// NewQueryerMock returns a mock for Queryer
func NewQueryerMock(t minimock.Tester) *QueryerMock {
	m := &QueryerMock{t: t}
	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.ScanMock = mQueryerMockScan{mock: m}
	m.ScanMock.callArgs = []*QueryerMockScanParams{}

	m.ScanOneMock = mQueryerMockScanOne{mock: m}
	m.ScanOneMock.callArgs = []*QueryerMockScanOneParams{}

	m.UpdateMock = mQueryerMockUpdate{mock: m}
	m.UpdateMock.callArgs = []*QueryerMockUpdateParams{}

	m.UpdateAndGetLastInsertIDMock = mQueryerMockUpdateAndGetLastInsertID{mock: m}
	m.UpdateAndGetLastInsertIDMock.callArgs = []*QueryerMockUpdateAndGetLastInsertIDParams{}

	m.UpdateAndGetRowsAffectedMock = mQueryerMockUpdateAndGetRowsAffected{mock: m}
	m.UpdateAndGetRowsAffectedMock.callArgs = []*QueryerMockUpdateAndGetRowsAffectedParams{}

	return m
}

type mQueryerMockScan struct {
	mock               *QueryerMock
	defaultExpectation *QueryerMockScanExpectation
	expectations       []*QueryerMockScanExpectation

	callArgs []*QueryerMockScanParams
	mutex    sync.RWMutex
}

// QueryerMockScanExpectation specifies expectation struct of the Queryer.Scan
type QueryerMockScanExpectation struct {
	mock    *QueryerMock
	params  *QueryerMockScanParams
	results *QueryerMockScanResults
	Counter uint64
}

// QueryerMockScanParams contains parameters of the Queryer.Scan
type QueryerMockScanParams struct {
	ctx     context.Context
	scanner RowScanner
	sql     string
	args    []interface{}
}

// QueryerMockScanResults contains results of the Queryer.Scan
type QueryerMockScanResults struct {
	err error
}

// Expect sets up expected params for Queryer.Scan
func (mmScan *mQueryerMockScan) Expect(ctx context.Context, scanner RowScanner, sql string, args ...interface{}) *mQueryerMockScan {
	if mmScan.mock.funcScan != nil {
		mmScan.mock.t.Fatalf("QueryerMock.Scan mock is already set by Set")
	}

	if mmScan.defaultExpectation == nil {
		mmScan.defaultExpectation = &QueryerMockScanExpectation{}
	}

	mmScan.defaultExpectation.params = &QueryerMockScanParams{ctx, scanner, sql, args}
	for _, e := range mmScan.expectations {
		if minimock.Equal(e.params, mmScan.defaultExpectation.params) {
			mmScan.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmScan.defaultExpectation.params)
		}
	}

	return mmScan
}

// Inspect accepts an inspector function that has same arguments as the Queryer.Scan
func (mmScan *mQueryerMockScan) Inspect(f func(ctx context.Context, scanner RowScanner, sql string, args ...interface{})) *mQueryerMockScan {
	if mmScan.mock.inspectFuncScan != nil {
		mmScan.mock.t.Fatalf("Inspect function is already set for QueryerMock.Scan")
	}

	mmScan.mock.inspectFuncScan = f

	return mmScan
}

// Return sets up results that will be returned by Queryer.Scan
func (mmScan *mQueryerMockScan) Return(err error) *QueryerMock {
	if mmScan.mock.funcScan != nil {
		mmScan.mock.t.Fatalf("QueryerMock.Scan mock is already set by Set")
	}

	if mmScan.defaultExpectation == nil {
		mmScan.defaultExpectation = &QueryerMockScanExpectation{mock: mmScan.mock}
	}
	mmScan.defaultExpectation.results = &QueryerMockScanResults{err}
	return mmScan.mock
}

//Set uses given function f to mock the Queryer.Scan method
func (mmScan *mQueryerMockScan) Set(f func(ctx context.Context, scanner RowScanner, sql string, args ...interface{}) (err error)) *QueryerMock {
	if mmScan.defaultExpectation != nil {
		mmScan.mock.t.Fatalf("Default expectation is already set for the Queryer.Scan method")
	}

	if len(mmScan.expectations) > 0 {
		mmScan.mock.t.Fatalf("Some expectations are already set for the Queryer.Scan method")
	}

	mmScan.mock.funcScan = f
	return mmScan.mock
}

// When sets expectation for the Queryer.Scan which will trigger the result defined by the following
// Then helper
func (mmScan *mQueryerMockScan) When(ctx context.Context, scanner RowScanner, sql string, args ...interface{}) *QueryerMockScanExpectation {
	if mmScan.mock.funcScan != nil {
		mmScan.mock.t.Fatalf("QueryerMock.Scan mock is already set by Set")
	}

	expectation := &QueryerMockScanExpectation{
		mock:   mmScan.mock,
		params: &QueryerMockScanParams{ctx, scanner, sql, args},
	}
	mmScan.expectations = append(mmScan.expectations, expectation)
	return expectation
}

// Then sets up Queryer.Scan return parameters for the expectation previously defined by the When method
func (e *QueryerMockScanExpectation) Then(err error) *QueryerMock {
	e.results = &QueryerMockScanResults{err}
	return e.mock
}

// Scan implements Queryer
func (mmScan *QueryerMock) Scan(ctx context.Context, scanner RowScanner, sql string, args ...interface{}) (err error) {
	mm_atomic.AddUint64(&mmScan.beforeScanCounter, 1)
	defer mm_atomic.AddUint64(&mmScan.afterScanCounter, 1)

	if mmScan.inspectFuncScan != nil {
		mmScan.inspectFuncScan(ctx, scanner, sql, args...)
	}

	mm_params := &QueryerMockScanParams{ctx, scanner, sql, args}

	// Record call args
	mmScan.ScanMock.mutex.Lock()
	mmScan.ScanMock.callArgs = append(mmScan.ScanMock.callArgs, mm_params)
	mmScan.ScanMock.mutex.Unlock()

	for _, e := range mmScan.ScanMock.expectations {
		if minimock.Equal(e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmScan.ScanMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmScan.ScanMock.defaultExpectation.Counter, 1)
		mm_want := mmScan.ScanMock.defaultExpectation.params
		mm_got := QueryerMockScanParams{ctx, scanner, sql, args}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmScan.t.Errorf("QueryerMock.Scan got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmScan.ScanMock.defaultExpectation.results
		if mm_results == nil {
			mmScan.t.Fatal("No results are set for the QueryerMock.Scan")
		}
		return (*mm_results).err
	}
	if mmScan.funcScan != nil {
		return mmScan.funcScan(ctx, scanner, sql, args...)
	}
	mmScan.t.Fatalf("Unexpected call to QueryerMock.Scan. %v %v %v %v", ctx, scanner, sql, args)
	return
}

// ScanAfterCounter returns a count of finished QueryerMock.Scan invocations
func (mmScan *QueryerMock) ScanAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmScan.afterScanCounter)
}

// ScanBeforeCounter returns a count of QueryerMock.Scan invocations
func (mmScan *QueryerMock) ScanBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmScan.beforeScanCounter)
}

// Calls returns a list of arguments used in each call to QueryerMock.Scan.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmScan *mQueryerMockScan) Calls() []*QueryerMockScanParams {
	mmScan.mutex.RLock()

	argCopy := make([]*QueryerMockScanParams, len(mmScan.callArgs))
	copy(argCopy, mmScan.callArgs)

	mmScan.mutex.RUnlock()

	return argCopy
}

// MinimockScanDone returns true if the count of the Scan invocations corresponds
// the number of defined expectations
func (m *QueryerMock) MinimockScanDone() bool {
	for _, e := range m.ScanMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.ScanMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterScanCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcScan != nil && mm_atomic.LoadUint64(&m.afterScanCounter) < 1 {
		return false
	}
	return true
}

// MinimockScanInspect logs each unmet expectation
func (m *QueryerMock) MinimockScanInspect() {
	for _, e := range m.ScanMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to QueryerMock.Scan with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.ScanMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterScanCounter) < 1 {
		if m.ScanMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to QueryerMock.Scan")
		} else {
			m.t.Errorf("Expected call to QueryerMock.Scan with params: %#v", *m.ScanMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcScan != nil && mm_atomic.LoadUint64(&m.afterScanCounter) < 1 {
		m.t.Error("Expected call to QueryerMock.Scan")
	}
}

type mQueryerMockScanOne struct {
	mock               *QueryerMock
	defaultExpectation *QueryerMockScanOneExpectation
	expectations       []*QueryerMockScanOneExpectation

	callArgs []*QueryerMockScanOneParams
	mutex    sync.RWMutex
}

// QueryerMockScanOneExpectation specifies expectation struct of the Queryer.ScanOne
type QueryerMockScanOneExpectation struct {
	mock    *QueryerMock
	params  *QueryerMockScanOneParams
	results *QueryerMockScanOneResults
	Counter uint64
}

// QueryerMockScanOneParams contains parameters of the Queryer.ScanOne
type QueryerMockScanOneParams struct {
	ctx     context.Context
	scanner RowScanner
	sql     string
	args    []interface{}
}

// QueryerMockScanOneResults contains results of the Queryer.ScanOne
type QueryerMockScanOneResults struct {
	err error
}

// Expect sets up expected params for Queryer.ScanOne
func (mmScanOne *mQueryerMockScanOne) Expect(ctx context.Context, scanner RowScanner, sql string, args ...interface{}) *mQueryerMockScanOne {
	if mmScanOne.mock.funcScanOne != nil {
		mmScanOne.mock.t.Fatalf("QueryerMock.ScanOne mock is already set by Set")
	}

	if mmScanOne.defaultExpectation == nil {
		mmScanOne.defaultExpectation = &QueryerMockScanOneExpectation{}
	}

	mmScanOne.defaultExpectation.params = &QueryerMockScanOneParams{ctx, scanner, sql, args}
	for _, e := range mmScanOne.expectations {
		if minimock.Equal(e.params, mmScanOne.defaultExpectation.params) {
			mmScanOne.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmScanOne.defaultExpectation.params)
		}
	}

	return mmScanOne
}

// Inspect accepts an inspector function that has same arguments as the Queryer.ScanOne
func (mmScanOne *mQueryerMockScanOne) Inspect(f func(ctx context.Context, scanner RowScanner, sql string, args ...interface{})) *mQueryerMockScanOne {
	if mmScanOne.mock.inspectFuncScanOne != nil {
		mmScanOne.mock.t.Fatalf("Inspect function is already set for QueryerMock.ScanOne")
	}

	mmScanOne.mock.inspectFuncScanOne = f

	return mmScanOne
}

// Return sets up results that will be returned by Queryer.ScanOne
func (mmScanOne *mQueryerMockScanOne) Return(err error) *QueryerMock {
	if mmScanOne.mock.funcScanOne != nil {
		mmScanOne.mock.t.Fatalf("QueryerMock.ScanOne mock is already set by Set")
	}

	if mmScanOne.defaultExpectation == nil {
		mmScanOne.defaultExpectation = &QueryerMockScanOneExpectation{mock: mmScanOne.mock}
	}
	mmScanOne.defaultExpectation.results = &QueryerMockScanOneResults{err}
	return mmScanOne.mock
}

//Set uses given function f to mock the Queryer.ScanOne method
func (mmScanOne *mQueryerMockScanOne) Set(f func(ctx context.Context, scanner RowScanner, sql string, args ...interface{}) (err error)) *QueryerMock {
	if mmScanOne.defaultExpectation != nil {
		mmScanOne.mock.t.Fatalf("Default expectation is already set for the Queryer.ScanOne method")
	}

	if len(mmScanOne.expectations) > 0 {
		mmScanOne.mock.t.Fatalf("Some expectations are already set for the Queryer.ScanOne method")
	}

	mmScanOne.mock.funcScanOne = f
	return mmScanOne.mock
}

// When sets expectation for the Queryer.ScanOne which will trigger the result defined by the following
// Then helper
func (mmScanOne *mQueryerMockScanOne) When(ctx context.Context, scanner RowScanner, sql string, args ...interface{}) *QueryerMockScanOneExpectation {
	if mmScanOne.mock.funcScanOne != nil {
		mmScanOne.mock.t.Fatalf("QueryerMock.ScanOne mock is already set by Set")
	}

	expectation := &QueryerMockScanOneExpectation{
		mock:   mmScanOne.mock,
		params: &QueryerMockScanOneParams{ctx, scanner, sql, args},
	}
	mmScanOne.expectations = append(mmScanOne.expectations, expectation)
	return expectation
}

// Then sets up Queryer.ScanOne return parameters for the expectation previously defined by the When method
func (e *QueryerMockScanOneExpectation) Then(err error) *QueryerMock {
	e.results = &QueryerMockScanOneResults{err}
	return e.mock
}

// ScanOne implements Queryer
func (mmScanOne *QueryerMock) ScanOne(ctx context.Context, scanner RowScanner, sql string, args ...interface{}) (err error) {
	mm_atomic.AddUint64(&mmScanOne.beforeScanOneCounter, 1)
	defer mm_atomic.AddUint64(&mmScanOne.afterScanOneCounter, 1)

	if mmScanOne.inspectFuncScanOne != nil {
		mmScanOne.inspectFuncScanOne(ctx, scanner, sql, args...)
	}

	mm_params := &QueryerMockScanOneParams{ctx, scanner, sql, args}

	// Record call args
	mmScanOne.ScanOneMock.mutex.Lock()
	mmScanOne.ScanOneMock.callArgs = append(mmScanOne.ScanOneMock.callArgs, mm_params)
	mmScanOne.ScanOneMock.mutex.Unlock()

	for _, e := range mmScanOne.ScanOneMock.expectations {
		if minimock.Equal(e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmScanOne.ScanOneMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmScanOne.ScanOneMock.defaultExpectation.Counter, 1)
		mm_want := mmScanOne.ScanOneMock.defaultExpectation.params
		mm_got := QueryerMockScanOneParams{ctx, scanner, sql, args}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmScanOne.t.Errorf("QueryerMock.ScanOne got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmScanOne.ScanOneMock.defaultExpectation.results
		if mm_results == nil {
			mmScanOne.t.Fatal("No results are set for the QueryerMock.ScanOne")
		}
		return (*mm_results).err
	}
	if mmScanOne.funcScanOne != nil {
		return mmScanOne.funcScanOne(ctx, scanner, sql, args...)
	}
	mmScanOne.t.Fatalf("Unexpected call to QueryerMock.ScanOne. %v %v %v %v", ctx, scanner, sql, args)
	return
}

// ScanOneAfterCounter returns a count of finished QueryerMock.ScanOne invocations
func (mmScanOne *QueryerMock) ScanOneAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmScanOne.afterScanOneCounter)
}

// ScanOneBeforeCounter returns a count of QueryerMock.ScanOne invocations
func (mmScanOne *QueryerMock) ScanOneBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmScanOne.beforeScanOneCounter)
}

// Calls returns a list of arguments used in each call to QueryerMock.ScanOne.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmScanOne *mQueryerMockScanOne) Calls() []*QueryerMockScanOneParams {
	mmScanOne.mutex.RLock()

	argCopy := make([]*QueryerMockScanOneParams, len(mmScanOne.callArgs))
	copy(argCopy, mmScanOne.callArgs)

	mmScanOne.mutex.RUnlock()

	return argCopy
}

// MinimockScanOneDone returns true if the count of the ScanOne invocations corresponds
// the number of defined expectations
func (m *QueryerMock) MinimockScanOneDone() bool {
	for _, e := range m.ScanOneMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.ScanOneMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterScanOneCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcScanOne != nil && mm_atomic.LoadUint64(&m.afterScanOneCounter) < 1 {
		return false
	}
	return true
}

// MinimockScanOneInspect logs each unmet expectation
func (m *QueryerMock) MinimockScanOneInspect() {
	for _, e := range m.ScanOneMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to QueryerMock.ScanOne with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.ScanOneMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterScanOneCounter) < 1 {
		if m.ScanOneMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to QueryerMock.ScanOne")
		} else {
			m.t.Errorf("Expected call to QueryerMock.ScanOne with params: %#v", *m.ScanOneMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcScanOne != nil && mm_atomic.LoadUint64(&m.afterScanOneCounter) < 1 {
		m.t.Error("Expected call to QueryerMock.ScanOne")
	}
}

type mQueryerMockUpdate struct {
	mock               *QueryerMock
	defaultExpectation *QueryerMockUpdateExpectation
	expectations       []*QueryerMockUpdateExpectation

	callArgs []*QueryerMockUpdateParams
	mutex    sync.RWMutex
}

// QueryerMockUpdateExpectation specifies expectation struct of the Queryer.Update
type QueryerMockUpdateExpectation struct {
	mock    *QueryerMock
	params  *QueryerMockUpdateParams
	results *QueryerMockUpdateResults
	Counter uint64
}

// QueryerMockUpdateParams contains parameters of the Queryer.Update
type QueryerMockUpdateParams struct {
	ctx  context.Context
	sql  string
	args []interface{}
}

// QueryerMockUpdateResults contains results of the Queryer.Update
type QueryerMockUpdateResults struct {
	r1  sql.Result
	err error
}

// Expect sets up expected params for Queryer.Update
func (mmUpdate *mQueryerMockUpdate) Expect(ctx context.Context, sql string, args ...interface{}) *mQueryerMockUpdate {
	if mmUpdate.mock.funcUpdate != nil {
		mmUpdate.mock.t.Fatalf("QueryerMock.Update mock is already set by Set")
	}

	if mmUpdate.defaultExpectation == nil {
		mmUpdate.defaultExpectation = &QueryerMockUpdateExpectation{}
	}

	mmUpdate.defaultExpectation.params = &QueryerMockUpdateParams{ctx, sql, args}
	for _, e := range mmUpdate.expectations {
		if minimock.Equal(e.params, mmUpdate.defaultExpectation.params) {
			mmUpdate.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmUpdate.defaultExpectation.params)
		}
	}

	return mmUpdate
}

// Inspect accepts an inspector function that has same arguments as the Queryer.Update
func (mmUpdate *mQueryerMockUpdate) Inspect(f func(ctx context.Context, sql string, args ...interface{})) *mQueryerMockUpdate {
	if mmUpdate.mock.inspectFuncUpdate != nil {
		mmUpdate.mock.t.Fatalf("Inspect function is already set for QueryerMock.Update")
	}

	mmUpdate.mock.inspectFuncUpdate = f

	return mmUpdate
}

// Return sets up results that will be returned by Queryer.Update
func (mmUpdate *mQueryerMockUpdate) Return(r1 sql.Result, err error) *QueryerMock {
	if mmUpdate.mock.funcUpdate != nil {
		mmUpdate.mock.t.Fatalf("QueryerMock.Update mock is already set by Set")
	}

	if mmUpdate.defaultExpectation == nil {
		mmUpdate.defaultExpectation = &QueryerMockUpdateExpectation{mock: mmUpdate.mock}
	}
	mmUpdate.defaultExpectation.results = &QueryerMockUpdateResults{r1, err}
	return mmUpdate.mock
}

//Set uses given function f to mock the Queryer.Update method
func (mmUpdate *mQueryerMockUpdate) Set(f func(ctx context.Context, sql string, args ...interface{}) (r1 sql.Result, err error)) *QueryerMock {
	if mmUpdate.defaultExpectation != nil {
		mmUpdate.mock.t.Fatalf("Default expectation is already set for the Queryer.Update method")
	}

	if len(mmUpdate.expectations) > 0 {
		mmUpdate.mock.t.Fatalf("Some expectations are already set for the Queryer.Update method")
	}

	mmUpdate.mock.funcUpdate = f
	return mmUpdate.mock
}

// When sets expectation for the Queryer.Update which will trigger the result defined by the following
// Then helper
func (mmUpdate *mQueryerMockUpdate) When(ctx context.Context, sql string, args ...interface{}) *QueryerMockUpdateExpectation {
	if mmUpdate.mock.funcUpdate != nil {
		mmUpdate.mock.t.Fatalf("QueryerMock.Update mock is already set by Set")
	}

	expectation := &QueryerMockUpdateExpectation{
		mock:   mmUpdate.mock,
		params: &QueryerMockUpdateParams{ctx, sql, args},
	}
	mmUpdate.expectations = append(mmUpdate.expectations, expectation)
	return expectation
}

// Then sets up Queryer.Update return parameters for the expectation previously defined by the When method
func (e *QueryerMockUpdateExpectation) Then(r1 sql.Result, err error) *QueryerMock {
	e.results = &QueryerMockUpdateResults{r1, err}
	return e.mock
}

// Update implements Queryer
func (mmUpdate *QueryerMock) Update(ctx context.Context, sql string, args ...interface{}) (r1 sql.Result, err error) {
	mm_atomic.AddUint64(&mmUpdate.beforeUpdateCounter, 1)
	defer mm_atomic.AddUint64(&mmUpdate.afterUpdateCounter, 1)

	if mmUpdate.inspectFuncUpdate != nil {
		mmUpdate.inspectFuncUpdate(ctx, sql, args...)
	}

	mm_params := &QueryerMockUpdateParams{ctx, sql, args}

	// Record call args
	mmUpdate.UpdateMock.mutex.Lock()
	mmUpdate.UpdateMock.callArgs = append(mmUpdate.UpdateMock.callArgs, mm_params)
	mmUpdate.UpdateMock.mutex.Unlock()

	for _, e := range mmUpdate.UpdateMock.expectations {
		if minimock.Equal(e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.r1, e.results.err
		}
	}

	if mmUpdate.UpdateMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmUpdate.UpdateMock.defaultExpectation.Counter, 1)
		mm_want := mmUpdate.UpdateMock.defaultExpectation.params
		mm_got := QueryerMockUpdateParams{ctx, sql, args}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmUpdate.t.Errorf("QueryerMock.Update got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmUpdate.UpdateMock.defaultExpectation.results
		if mm_results == nil {
			mmUpdate.t.Fatal("No results are set for the QueryerMock.Update")
		}
		return (*mm_results).r1, (*mm_results).err
	}
	if mmUpdate.funcUpdate != nil {
		return mmUpdate.funcUpdate(ctx, sql, args...)
	}
	mmUpdate.t.Fatalf("Unexpected call to QueryerMock.Update. %v %v %v", ctx, sql, args)
	return
}

// UpdateAfterCounter returns a count of finished QueryerMock.Update invocations
func (mmUpdate *QueryerMock) UpdateAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmUpdate.afterUpdateCounter)
}

// UpdateBeforeCounter returns a count of QueryerMock.Update invocations
func (mmUpdate *QueryerMock) UpdateBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmUpdate.beforeUpdateCounter)
}

// Calls returns a list of arguments used in each call to QueryerMock.Update.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmUpdate *mQueryerMockUpdate) Calls() []*QueryerMockUpdateParams {
	mmUpdate.mutex.RLock()

	argCopy := make([]*QueryerMockUpdateParams, len(mmUpdate.callArgs))
	copy(argCopy, mmUpdate.callArgs)

	mmUpdate.mutex.RUnlock()

	return argCopy
}

// MinimockUpdateDone returns true if the count of the Update invocations corresponds
// the number of defined expectations
func (m *QueryerMock) MinimockUpdateDone() bool {
	for _, e := range m.UpdateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.UpdateMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterUpdateCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcUpdate != nil && mm_atomic.LoadUint64(&m.afterUpdateCounter) < 1 {
		return false
	}
	return true
}

// MinimockUpdateInspect logs each unmet expectation
func (m *QueryerMock) MinimockUpdateInspect() {
	for _, e := range m.UpdateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to QueryerMock.Update with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.UpdateMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterUpdateCounter) < 1 {
		if m.UpdateMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to QueryerMock.Update")
		} else {
			m.t.Errorf("Expected call to QueryerMock.Update with params: %#v", *m.UpdateMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcUpdate != nil && mm_atomic.LoadUint64(&m.afterUpdateCounter) < 1 {
		m.t.Error("Expected call to QueryerMock.Update")
	}
}

type mQueryerMockUpdateAndGetLastInsertID struct {
	mock               *QueryerMock
	defaultExpectation *QueryerMockUpdateAndGetLastInsertIDExpectation
	expectations       []*QueryerMockUpdateAndGetLastInsertIDExpectation

	callArgs []*QueryerMockUpdateAndGetLastInsertIDParams
	mutex    sync.RWMutex
}

// QueryerMockUpdateAndGetLastInsertIDExpectation specifies expectation struct of the Queryer.UpdateAndGetLastInsertID
type QueryerMockUpdateAndGetLastInsertIDExpectation struct {
	mock    *QueryerMock
	params  *QueryerMockUpdateAndGetLastInsertIDParams
	results *QueryerMockUpdateAndGetLastInsertIDResults
	Counter uint64
}

// QueryerMockUpdateAndGetLastInsertIDParams contains parameters of the Queryer.UpdateAndGetLastInsertID
type QueryerMockUpdateAndGetLastInsertIDParams struct {
	ctx  context.Context
	sql  string
	args []interface{}
}

// QueryerMockUpdateAndGetLastInsertIDResults contains results of the Queryer.UpdateAndGetLastInsertID
type QueryerMockUpdateAndGetLastInsertIDResults struct {
	i1  int64
	err error
}

// Expect sets up expected params for Queryer.UpdateAndGetLastInsertID
func (mmUpdateAndGetLastInsertID *mQueryerMockUpdateAndGetLastInsertID) Expect(ctx context.Context, sql string, args ...interface{}) *mQueryerMockUpdateAndGetLastInsertID {
	if mmUpdateAndGetLastInsertID.mock.funcUpdateAndGetLastInsertID != nil {
		mmUpdateAndGetLastInsertID.mock.t.Fatalf("QueryerMock.UpdateAndGetLastInsertID mock is already set by Set")
	}

	if mmUpdateAndGetLastInsertID.defaultExpectation == nil {
		mmUpdateAndGetLastInsertID.defaultExpectation = &QueryerMockUpdateAndGetLastInsertIDExpectation{}
	}

	mmUpdateAndGetLastInsertID.defaultExpectation.params = &QueryerMockUpdateAndGetLastInsertIDParams{ctx, sql, args}
	for _, e := range mmUpdateAndGetLastInsertID.expectations {
		if minimock.Equal(e.params, mmUpdateAndGetLastInsertID.defaultExpectation.params) {
			mmUpdateAndGetLastInsertID.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmUpdateAndGetLastInsertID.defaultExpectation.params)
		}
	}

	return mmUpdateAndGetLastInsertID
}

// Inspect accepts an inspector function that has same arguments as the Queryer.UpdateAndGetLastInsertID
func (mmUpdateAndGetLastInsertID *mQueryerMockUpdateAndGetLastInsertID) Inspect(f func(ctx context.Context, sql string, args ...interface{})) *mQueryerMockUpdateAndGetLastInsertID {
	if mmUpdateAndGetLastInsertID.mock.inspectFuncUpdateAndGetLastInsertID != nil {
		mmUpdateAndGetLastInsertID.mock.t.Fatalf("Inspect function is already set for QueryerMock.UpdateAndGetLastInsertID")
	}

	mmUpdateAndGetLastInsertID.mock.inspectFuncUpdateAndGetLastInsertID = f

	return mmUpdateAndGetLastInsertID
}

// Return sets up results that will be returned by Queryer.UpdateAndGetLastInsertID
func (mmUpdateAndGetLastInsertID *mQueryerMockUpdateAndGetLastInsertID) Return(i1 int64, err error) *QueryerMock {
	if mmUpdateAndGetLastInsertID.mock.funcUpdateAndGetLastInsertID != nil {
		mmUpdateAndGetLastInsertID.mock.t.Fatalf("QueryerMock.UpdateAndGetLastInsertID mock is already set by Set")
	}

	if mmUpdateAndGetLastInsertID.defaultExpectation == nil {
		mmUpdateAndGetLastInsertID.defaultExpectation = &QueryerMockUpdateAndGetLastInsertIDExpectation{mock: mmUpdateAndGetLastInsertID.mock}
	}
	mmUpdateAndGetLastInsertID.defaultExpectation.results = &QueryerMockUpdateAndGetLastInsertIDResults{i1, err}
	return mmUpdateAndGetLastInsertID.mock
}

//Set uses given function f to mock the Queryer.UpdateAndGetLastInsertID method
func (mmUpdateAndGetLastInsertID *mQueryerMockUpdateAndGetLastInsertID) Set(f func(ctx context.Context, sql string, args ...interface{}) (i1 int64, err error)) *QueryerMock {
	if mmUpdateAndGetLastInsertID.defaultExpectation != nil {
		mmUpdateAndGetLastInsertID.mock.t.Fatalf("Default expectation is already set for the Queryer.UpdateAndGetLastInsertID method")
	}

	if len(mmUpdateAndGetLastInsertID.expectations) > 0 {
		mmUpdateAndGetLastInsertID.mock.t.Fatalf("Some expectations are already set for the Queryer.UpdateAndGetLastInsertID method")
	}

	mmUpdateAndGetLastInsertID.mock.funcUpdateAndGetLastInsertID = f
	return mmUpdateAndGetLastInsertID.mock
}

// When sets expectation for the Queryer.UpdateAndGetLastInsertID which will trigger the result defined by the following
// Then helper
func (mmUpdateAndGetLastInsertID *mQueryerMockUpdateAndGetLastInsertID) When(ctx context.Context, sql string, args ...interface{}) *QueryerMockUpdateAndGetLastInsertIDExpectation {
	if mmUpdateAndGetLastInsertID.mock.funcUpdateAndGetLastInsertID != nil {
		mmUpdateAndGetLastInsertID.mock.t.Fatalf("QueryerMock.UpdateAndGetLastInsertID mock is already set by Set")
	}

	expectation := &QueryerMockUpdateAndGetLastInsertIDExpectation{
		mock:   mmUpdateAndGetLastInsertID.mock,
		params: &QueryerMockUpdateAndGetLastInsertIDParams{ctx, sql, args},
	}
	mmUpdateAndGetLastInsertID.expectations = append(mmUpdateAndGetLastInsertID.expectations, expectation)
	return expectation
}

// Then sets up Queryer.UpdateAndGetLastInsertID return parameters for the expectation previously defined by the When method
func (e *QueryerMockUpdateAndGetLastInsertIDExpectation) Then(i1 int64, err error) *QueryerMock {
	e.results = &QueryerMockUpdateAndGetLastInsertIDResults{i1, err}
	return e.mock
}

// UpdateAndGetLastInsertID implements Queryer
func (mmUpdateAndGetLastInsertID *QueryerMock) UpdateAndGetLastInsertID(ctx context.Context, sql string, args ...interface{}) (i1 int64, err error) {
	mm_atomic.AddUint64(&mmUpdateAndGetLastInsertID.beforeUpdateAndGetLastInsertIDCounter, 1)
	defer mm_atomic.AddUint64(&mmUpdateAndGetLastInsertID.afterUpdateAndGetLastInsertIDCounter, 1)

	if mmUpdateAndGetLastInsertID.inspectFuncUpdateAndGetLastInsertID != nil {
		mmUpdateAndGetLastInsertID.inspectFuncUpdateAndGetLastInsertID(ctx, sql, args...)
	}

	mm_params := &QueryerMockUpdateAndGetLastInsertIDParams{ctx, sql, args}

	// Record call args
	mmUpdateAndGetLastInsertID.UpdateAndGetLastInsertIDMock.mutex.Lock()
	mmUpdateAndGetLastInsertID.UpdateAndGetLastInsertIDMock.callArgs = append(mmUpdateAndGetLastInsertID.UpdateAndGetLastInsertIDMock.callArgs, mm_params)
	mmUpdateAndGetLastInsertID.UpdateAndGetLastInsertIDMock.mutex.Unlock()

	for _, e := range mmUpdateAndGetLastInsertID.UpdateAndGetLastInsertIDMock.expectations {
		if minimock.Equal(e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.i1, e.results.err
		}
	}

	if mmUpdateAndGetLastInsertID.UpdateAndGetLastInsertIDMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmUpdateAndGetLastInsertID.UpdateAndGetLastInsertIDMock.defaultExpectation.Counter, 1)
		mm_want := mmUpdateAndGetLastInsertID.UpdateAndGetLastInsertIDMock.defaultExpectation.params
		mm_got := QueryerMockUpdateAndGetLastInsertIDParams{ctx, sql, args}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmUpdateAndGetLastInsertID.t.Errorf("QueryerMock.UpdateAndGetLastInsertID got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmUpdateAndGetLastInsertID.UpdateAndGetLastInsertIDMock.defaultExpectation.results
		if mm_results == nil {
			mmUpdateAndGetLastInsertID.t.Fatal("No results are set for the QueryerMock.UpdateAndGetLastInsertID")
		}
		return (*mm_results).i1, (*mm_results).err
	}
	if mmUpdateAndGetLastInsertID.funcUpdateAndGetLastInsertID != nil {
		return mmUpdateAndGetLastInsertID.funcUpdateAndGetLastInsertID(ctx, sql, args...)
	}
	mmUpdateAndGetLastInsertID.t.Fatalf("Unexpected call to QueryerMock.UpdateAndGetLastInsertID. %v %v %v", ctx, sql, args)
	return
}

// UpdateAndGetLastInsertIDAfterCounter returns a count of finished QueryerMock.UpdateAndGetLastInsertID invocations
func (mmUpdateAndGetLastInsertID *QueryerMock) UpdateAndGetLastInsertIDAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmUpdateAndGetLastInsertID.afterUpdateAndGetLastInsertIDCounter)
}

// UpdateAndGetLastInsertIDBeforeCounter returns a count of QueryerMock.UpdateAndGetLastInsertID invocations
func (mmUpdateAndGetLastInsertID *QueryerMock) UpdateAndGetLastInsertIDBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmUpdateAndGetLastInsertID.beforeUpdateAndGetLastInsertIDCounter)
}

// Calls returns a list of arguments used in each call to QueryerMock.UpdateAndGetLastInsertID.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmUpdateAndGetLastInsertID *mQueryerMockUpdateAndGetLastInsertID) Calls() []*QueryerMockUpdateAndGetLastInsertIDParams {
	mmUpdateAndGetLastInsertID.mutex.RLock()

	argCopy := make([]*QueryerMockUpdateAndGetLastInsertIDParams, len(mmUpdateAndGetLastInsertID.callArgs))
	copy(argCopy, mmUpdateAndGetLastInsertID.callArgs)

	mmUpdateAndGetLastInsertID.mutex.RUnlock()

	return argCopy
}

// MinimockUpdateAndGetLastInsertIDDone returns true if the count of the UpdateAndGetLastInsertID invocations corresponds
// the number of defined expectations
func (m *QueryerMock) MinimockUpdateAndGetLastInsertIDDone() bool {
	for _, e := range m.UpdateAndGetLastInsertIDMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.UpdateAndGetLastInsertIDMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterUpdateAndGetLastInsertIDCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcUpdateAndGetLastInsertID != nil && mm_atomic.LoadUint64(&m.afterUpdateAndGetLastInsertIDCounter) < 1 {
		return false
	}
	return true
}

// MinimockUpdateAndGetLastInsertIDInspect logs each unmet expectation
func (m *QueryerMock) MinimockUpdateAndGetLastInsertIDInspect() {
	for _, e := range m.UpdateAndGetLastInsertIDMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to QueryerMock.UpdateAndGetLastInsertID with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.UpdateAndGetLastInsertIDMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterUpdateAndGetLastInsertIDCounter) < 1 {
		if m.UpdateAndGetLastInsertIDMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to QueryerMock.UpdateAndGetLastInsertID")
		} else {
			m.t.Errorf("Expected call to QueryerMock.UpdateAndGetLastInsertID with params: %#v", *m.UpdateAndGetLastInsertIDMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcUpdateAndGetLastInsertID != nil && mm_atomic.LoadUint64(&m.afterUpdateAndGetLastInsertIDCounter) < 1 {
		m.t.Error("Expected call to QueryerMock.UpdateAndGetLastInsertID")
	}
}

type mQueryerMockUpdateAndGetRowsAffected struct {
	mock               *QueryerMock
	defaultExpectation *QueryerMockUpdateAndGetRowsAffectedExpectation
	expectations       []*QueryerMockUpdateAndGetRowsAffectedExpectation

	callArgs []*QueryerMockUpdateAndGetRowsAffectedParams
	mutex    sync.RWMutex
}

// QueryerMockUpdateAndGetRowsAffectedExpectation specifies expectation struct of the Queryer.UpdateAndGetRowsAffected
type QueryerMockUpdateAndGetRowsAffectedExpectation struct {
	mock    *QueryerMock
	params  *QueryerMockUpdateAndGetRowsAffectedParams
	results *QueryerMockUpdateAndGetRowsAffectedResults
	Counter uint64
}

// QueryerMockUpdateAndGetRowsAffectedParams contains parameters of the Queryer.UpdateAndGetRowsAffected
type QueryerMockUpdateAndGetRowsAffectedParams struct {
	ctx  context.Context
	sql  string
	args []interface{}
}

// QueryerMockUpdateAndGetRowsAffectedResults contains results of the Queryer.UpdateAndGetRowsAffected
type QueryerMockUpdateAndGetRowsAffectedResults struct {
	i1  int64
	err error
}

// Expect sets up expected params for Queryer.UpdateAndGetRowsAffected
func (mmUpdateAndGetRowsAffected *mQueryerMockUpdateAndGetRowsAffected) Expect(ctx context.Context, sql string, args ...interface{}) *mQueryerMockUpdateAndGetRowsAffected {
	if mmUpdateAndGetRowsAffected.mock.funcUpdateAndGetRowsAffected != nil {
		mmUpdateAndGetRowsAffected.mock.t.Fatalf("QueryerMock.UpdateAndGetRowsAffected mock is already set by Set")
	}

	if mmUpdateAndGetRowsAffected.defaultExpectation == nil {
		mmUpdateAndGetRowsAffected.defaultExpectation = &QueryerMockUpdateAndGetRowsAffectedExpectation{}
	}

	mmUpdateAndGetRowsAffected.defaultExpectation.params = &QueryerMockUpdateAndGetRowsAffectedParams{ctx, sql, args}
	for _, e := range mmUpdateAndGetRowsAffected.expectations {
		if minimock.Equal(e.params, mmUpdateAndGetRowsAffected.defaultExpectation.params) {
			mmUpdateAndGetRowsAffected.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmUpdateAndGetRowsAffected.defaultExpectation.params)
		}
	}

	return mmUpdateAndGetRowsAffected
}

// Inspect accepts an inspector function that has same arguments as the Queryer.UpdateAndGetRowsAffected
func (mmUpdateAndGetRowsAffected *mQueryerMockUpdateAndGetRowsAffected) Inspect(f func(ctx context.Context, sql string, args ...interface{})) *mQueryerMockUpdateAndGetRowsAffected {
	if mmUpdateAndGetRowsAffected.mock.inspectFuncUpdateAndGetRowsAffected != nil {
		mmUpdateAndGetRowsAffected.mock.t.Fatalf("Inspect function is already set for QueryerMock.UpdateAndGetRowsAffected")
	}

	mmUpdateAndGetRowsAffected.mock.inspectFuncUpdateAndGetRowsAffected = f

	return mmUpdateAndGetRowsAffected
}

// Return sets up results that will be returned by Queryer.UpdateAndGetRowsAffected
func (mmUpdateAndGetRowsAffected *mQueryerMockUpdateAndGetRowsAffected) Return(i1 int64, err error) *QueryerMock {
	if mmUpdateAndGetRowsAffected.mock.funcUpdateAndGetRowsAffected != nil {
		mmUpdateAndGetRowsAffected.mock.t.Fatalf("QueryerMock.UpdateAndGetRowsAffected mock is already set by Set")
	}

	if mmUpdateAndGetRowsAffected.defaultExpectation == nil {
		mmUpdateAndGetRowsAffected.defaultExpectation = &QueryerMockUpdateAndGetRowsAffectedExpectation{mock: mmUpdateAndGetRowsAffected.mock}
	}
	mmUpdateAndGetRowsAffected.defaultExpectation.results = &QueryerMockUpdateAndGetRowsAffectedResults{i1, err}
	return mmUpdateAndGetRowsAffected.mock
}

//Set uses given function f to mock the Queryer.UpdateAndGetRowsAffected method
func (mmUpdateAndGetRowsAffected *mQueryerMockUpdateAndGetRowsAffected) Set(f func(ctx context.Context, sql string, args ...interface{}) (i1 int64, err error)) *QueryerMock {
	if mmUpdateAndGetRowsAffected.defaultExpectation != nil {
		mmUpdateAndGetRowsAffected.mock.t.Fatalf("Default expectation is already set for the Queryer.UpdateAndGetRowsAffected method")
	}

	if len(mmUpdateAndGetRowsAffected.expectations) > 0 {
		mmUpdateAndGetRowsAffected.mock.t.Fatalf("Some expectations are already set for the Queryer.UpdateAndGetRowsAffected method")
	}

	mmUpdateAndGetRowsAffected.mock.funcUpdateAndGetRowsAffected = f
	return mmUpdateAndGetRowsAffected.mock
}

// When sets expectation for the Queryer.UpdateAndGetRowsAffected which will trigger the result defined by the following
// Then helper
func (mmUpdateAndGetRowsAffected *mQueryerMockUpdateAndGetRowsAffected) When(ctx context.Context, sql string, args ...interface{}) *QueryerMockUpdateAndGetRowsAffectedExpectation {
	if mmUpdateAndGetRowsAffected.mock.funcUpdateAndGetRowsAffected != nil {
		mmUpdateAndGetRowsAffected.mock.t.Fatalf("QueryerMock.UpdateAndGetRowsAffected mock is already set by Set")
	}

	expectation := &QueryerMockUpdateAndGetRowsAffectedExpectation{
		mock:   mmUpdateAndGetRowsAffected.mock,
		params: &QueryerMockUpdateAndGetRowsAffectedParams{ctx, sql, args},
	}
	mmUpdateAndGetRowsAffected.expectations = append(mmUpdateAndGetRowsAffected.expectations, expectation)
	return expectation
}

// Then sets up Queryer.UpdateAndGetRowsAffected return parameters for the expectation previously defined by the When method
func (e *QueryerMockUpdateAndGetRowsAffectedExpectation) Then(i1 int64, err error) *QueryerMock {
	e.results = &QueryerMockUpdateAndGetRowsAffectedResults{i1, err}
	return e.mock
}

// UpdateAndGetRowsAffected implements Queryer
func (mmUpdateAndGetRowsAffected *QueryerMock) UpdateAndGetRowsAffected(ctx context.Context, sql string, args ...interface{}) (i1 int64, err error) {
	mm_atomic.AddUint64(&mmUpdateAndGetRowsAffected.beforeUpdateAndGetRowsAffectedCounter, 1)
	defer mm_atomic.AddUint64(&mmUpdateAndGetRowsAffected.afterUpdateAndGetRowsAffectedCounter, 1)

	if mmUpdateAndGetRowsAffected.inspectFuncUpdateAndGetRowsAffected != nil {
		mmUpdateAndGetRowsAffected.inspectFuncUpdateAndGetRowsAffected(ctx, sql, args...)
	}

	mm_params := &QueryerMockUpdateAndGetRowsAffectedParams{ctx, sql, args}

	// Record call args
	mmUpdateAndGetRowsAffected.UpdateAndGetRowsAffectedMock.mutex.Lock()
	mmUpdateAndGetRowsAffected.UpdateAndGetRowsAffectedMock.callArgs = append(mmUpdateAndGetRowsAffected.UpdateAndGetRowsAffectedMock.callArgs, mm_params)
	mmUpdateAndGetRowsAffected.UpdateAndGetRowsAffectedMock.mutex.Unlock()

	for _, e := range mmUpdateAndGetRowsAffected.UpdateAndGetRowsAffectedMock.expectations {
		if minimock.Equal(e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.i1, e.results.err
		}
	}

	if mmUpdateAndGetRowsAffected.UpdateAndGetRowsAffectedMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmUpdateAndGetRowsAffected.UpdateAndGetRowsAffectedMock.defaultExpectation.Counter, 1)
		mm_want := mmUpdateAndGetRowsAffected.UpdateAndGetRowsAffectedMock.defaultExpectation.params
		mm_got := QueryerMockUpdateAndGetRowsAffectedParams{ctx, sql, args}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmUpdateAndGetRowsAffected.t.Errorf("QueryerMock.UpdateAndGetRowsAffected got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmUpdateAndGetRowsAffected.UpdateAndGetRowsAffectedMock.defaultExpectation.results
		if mm_results == nil {
			mmUpdateAndGetRowsAffected.t.Fatal("No results are set for the QueryerMock.UpdateAndGetRowsAffected")
		}
		return (*mm_results).i1, (*mm_results).err
	}
	if mmUpdateAndGetRowsAffected.funcUpdateAndGetRowsAffected != nil {
		return mmUpdateAndGetRowsAffected.funcUpdateAndGetRowsAffected(ctx, sql, args...)
	}
	mmUpdateAndGetRowsAffected.t.Fatalf("Unexpected call to QueryerMock.UpdateAndGetRowsAffected. %v %v %v", ctx, sql, args)
	return
}

// UpdateAndGetRowsAffectedAfterCounter returns a count of finished QueryerMock.UpdateAndGetRowsAffected invocations
func (mmUpdateAndGetRowsAffected *QueryerMock) UpdateAndGetRowsAffectedAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmUpdateAndGetRowsAffected.afterUpdateAndGetRowsAffectedCounter)
}

// UpdateAndGetRowsAffectedBeforeCounter returns a count of QueryerMock.UpdateAndGetRowsAffected invocations
func (mmUpdateAndGetRowsAffected *QueryerMock) UpdateAndGetRowsAffectedBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmUpdateAndGetRowsAffected.beforeUpdateAndGetRowsAffectedCounter)
}

// Calls returns a list of arguments used in each call to QueryerMock.UpdateAndGetRowsAffected.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmUpdateAndGetRowsAffected *mQueryerMockUpdateAndGetRowsAffected) Calls() []*QueryerMockUpdateAndGetRowsAffectedParams {
	mmUpdateAndGetRowsAffected.mutex.RLock()

	argCopy := make([]*QueryerMockUpdateAndGetRowsAffectedParams, len(mmUpdateAndGetRowsAffected.callArgs))
	copy(argCopy, mmUpdateAndGetRowsAffected.callArgs)

	mmUpdateAndGetRowsAffected.mutex.RUnlock()

	return argCopy
}

// MinimockUpdateAndGetRowsAffectedDone returns true if the count of the UpdateAndGetRowsAffected invocations corresponds
// the number of defined expectations
func (m *QueryerMock) MinimockUpdateAndGetRowsAffectedDone() bool {
	for _, e := range m.UpdateAndGetRowsAffectedMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.UpdateAndGetRowsAffectedMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterUpdateAndGetRowsAffectedCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcUpdateAndGetRowsAffected != nil && mm_atomic.LoadUint64(&m.afterUpdateAndGetRowsAffectedCounter) < 1 {
		return false
	}
	return true
}

// MinimockUpdateAndGetRowsAffectedInspect logs each unmet expectation
func (m *QueryerMock) MinimockUpdateAndGetRowsAffectedInspect() {
	for _, e := range m.UpdateAndGetRowsAffectedMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to QueryerMock.UpdateAndGetRowsAffected with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.UpdateAndGetRowsAffectedMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterUpdateAndGetRowsAffectedCounter) < 1 {
		if m.UpdateAndGetRowsAffectedMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to QueryerMock.UpdateAndGetRowsAffected")
		} else {
			m.t.Errorf("Expected call to QueryerMock.UpdateAndGetRowsAffected with params: %#v", *m.UpdateAndGetRowsAffectedMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcUpdateAndGetRowsAffected != nil && mm_atomic.LoadUint64(&m.afterUpdateAndGetRowsAffectedCounter) < 1 {
		m.t.Error("Expected call to QueryerMock.UpdateAndGetRowsAffected")
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *QueryerMock) MinimockFinish() {
	if !m.minimockDone() {
		m.MinimockScanInspect()

		m.MinimockScanOneInspect()

		m.MinimockUpdateInspect()

		m.MinimockUpdateAndGetLastInsertIDInspect()

		m.MinimockUpdateAndGetRowsAffectedInspect()
		m.t.FailNow()
	}
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *QueryerMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *QueryerMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockScanDone() &&
		m.MinimockScanOneDone() &&
		m.MinimockUpdateDone() &&
		m.MinimockUpdateAndGetLastInsertIDDone() &&
		m.MinimockUpdateAndGetRowsAffectedDone()
}
